services:
  - type: web
    name: alma-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    runtime: node
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      # Aquí van tus variables .env (Render te pedirá que las llenes)
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        sync: false
      - key: APP_URL
        sync: false